services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
      # Anything we add or change in one the dirs will be reflected in the other dir too; they are in sync due to the mapping.
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
